kubikowski/set-utilities

.eslintrc.json
.run/test_scale.run.xml
package.json
src/test/constants/scale-testing-constants.ts
src/test/scale.test.ts

Scale tests are explicitly ignored in paths from the `npm test` command. To run them, use the `npm run test:scale` command instead.

added scale tests

---

src/index.ts
src/test/difference.function.test.ts
src/test/equivalence.function.test.ts
src/test/intersection.function.test.ts
src/test/scale.test.ts
src/test/sort.test.ts
src/test/union.function.test.ts
src/test/xor.function.test.ts

An export for `sort` was not added to the `index.ts` in #11. This aims to fix that export.

export `sort` from index

---

.eslintrc.json
.run/test_coverage.run.xml
package.json
src/functions/equivalence.function.ts
src/functions/subset.function.ts
src/functions/superset.function.ts
src/test/constants/sort-testing-constants.ts
src/test/constants/testing-constants.ts
src/test/equivalence.function.test.ts
src/test/scale.test.ts
src/test/sort.test.ts
src/test/subset.function.test.ts
src/test/superset.function.test.ts

Added code coverage testing. Adding more unit tests & corrected function syntax until coverage reached 100%.
Note: replaced some instance of `optional chaining` with known `non-null assertions`. Ex:
`sets[0] ?? new Set()` is now just `sets[0]!`.

added code coverage testing

---

src/operations/xor.function.ts

Improved xor performance using custom implementation rather than calling `difference` and `union` internally.
Using `difference` and `union` internally.
|          | xor of 1 set: 10M | xor of 2 sets: 10M & 5M | xor of 3 sets: 10M, 5M, & 3M |
|:---------|:------------------|:------------------------|:-----------------------------|
| test 1:  | 6629.388 ms       | 8918.653 ms             | 11540.040 ms                 |
| test 2:  | 6463.766 ms       | 8907.801 ms             | 11917.361 ms                 |
| test 3:  | 6566.865 ms       | 8812.364 ms             | 11522.295 ms                 |
| test 4:  | 6639.678 ms       | 8727.676 ms             | 11625.841 ms                 |
| test 5:  | 7025.046 ms       | 8848.937 ms             | 11584.064 ms                 |
| average: | …

improved xor performance

---

src/operations/difference.function.ts
src/operations/intersection.function.ts
src/operations/union.function.ts
test/constants/scale-testing-constants.ts
test/scale.test.ts

Replaced all `forEach` calls with imperative `for .. of` loops. These replacements happened in the `difference`, `intersection`, & `union` functions, all within the `operations` directory.
Unlike the rewriting of `xor` for #20, which cut down runtime by up to 50%, these `forEach` replacements only changed the total running time of each function on my machine by around 5%.
Moreover, each test run was handled at the whims of my machine's moment-to-moment cpu availability. To make the performance tests as robust as possible, I increased the Set size limit from `10 Mil` to `15 Mil`. However, there is a bug in V8 that causes sets of `size > 16,777,216` to error on `add` calls. So I could not reasonably increase this testing limit much higher.

marginally improved operations performances

---

README.md

1. `npm` version w/ download link
2. `license`
3. `fossa license status` w/ fossa app link
4. `install size` w/ package phobia link
5. `test job` w/ github actions link
6. `coverage %` w/ coveralls link
7. `language %` w/ typescriptlang link
Given that there is already a `fossa license status` badge, this section is duplicative.

added relevant badges to readme

---

test/constants/multiples.model.ts
test/scale.test.ts

Added 4 tests to each scale test suite, based on the following configurations:
1. `100` equivalent sets, each containing `100_000` values.
2. `10_000` equivalent sets, each containing `1_000` values.
3. `100` disjoint sets, each containing `100_000` values.
4. `10_000` disjoint sets, each containing `1_000` values.

added many sets to scale tests

---

src/operations/intersection.function.ts

`intersection` was originally written by generating a `new Set()` with the intersected values for each provided set. Then, loop over the values in each provided set, checking against the former result.
This rewrite changes `intersection` to only generate a single `new Set()` at the outset. Then, loop over the values in that `result` once for each provided set, checking against that provided set.
So, for instance. If after the first iteration there are 0 values in the `result` set, then `intersection` will stop checking for values in further result sets, and return immediately. This is what we see happen in `intersection(...someDisjoint)` test, where the run time is shown to be reduced by over 99%.
And we see this performance gain in less user optimized versions of the horizontal scale …

improved intersection performance

---

src/operations/difference.function.ts
src/operations/intersection.function.ts
src/operations/union.function.ts
src/operations/xor.function.ts

After some further testing, when there is no value provided at `sets[0]`, the resulting `new Set(undefined)` behaves equivalently to `new Set()`: it produces an empty set, without throwing an error.
So I have removed this instance of nullish coalescing on the resulting `new Set(undefined ?? new Set())`. In favor of simpler and cleaner code.

removed nullish coalescing

---

src/comparisons/disjoint.function.ts
src/comparisons/equivalence.function.ts
src/comparisons/proper-subset.function.ts
src/comparisons/proper-superset.function.ts
src/comparisons/subset.function.ts
src/comparisons/superset.function.ts
src/operations/difference.function.ts
src/operations/intersection.function.ts
src/operations/union.function.ts
src/operations/xor.function.ts
src/ordering/sort.function.ts

given that `element` is the proper mathematical term.

consistently renamed value to element

---

src/comparisons/disjoint.function.ts
src/comparisons/equivalence.function.ts
src/comparisons/proper-subset.function.ts
src/comparisons/proper-superset.function.ts
src/comparisons/subset.function.ts
src/comparisons/superset.function.ts
src/operations/difference.function.ts
src/operations/intersection.function.ts
src/operations/union.function.ts
src/operations/xor.function.ts

I personally find that the resulting code is more legible, using `sets.shift()` in conjunction with `for (const set of sets)`.
As an aside, this code style also removed all necessary usages of nullish coalescing.
Moreover, the refactored code resulted in an overall performance improvement of ~11% overall. This is generally due to the fact that we are not fetching `sets[index]` in each loop iteration, in favor of a pre-cached `const set`.
Testing Notes:
- All tests were run on a 2017 Razer Blade Pro, Core i7-7700HQ Processor, 64GB ram.
- All tests were run using the V8 JS engine.
- All timings is in ms
<details>
<summary><h3 style="display: inline">[original] raw data:</h3></summary>
| Original Overall Timing: | time (ms)   |
|--------------------------|-------------|
| Original Run Timing …

refactored funcitons to use `sets.shift()` & `for .. of`

---

src/comparisons/equivalence.function.ts
src/comparisons/proper-subset.function.ts
src/comparisons/proper-superset.function.ts
src/comparisons/subset.function.ts
src/comparisons/superset.function.ts

While I will admit that the booleans names were remarkably clear, they were in no way concise. And I found that the resulting code was overall less legible at a glance. So I have removed the named booleans in favor of inlining their `cardinalities.every()` in the respective if statements.

remove named booleans on cardinality comparisons

---

test/comparisons/disjoint.function.test.ts
test/comparisons/equivalence.function.test.ts
test/comparisons/proper-subset.function.test.ts
test/comparisons/proper-superset.function.test.ts
test/comparisons/subset.function.test.ts
test/comparisons/superset.function.test.ts
test/constants/sort-testing-constants.ts
test/constants/testing-constants.ts
test/operations/difference.function.test.ts
test/operations/intersection.function.test.ts
test/operations/union.function.test.ts
test/operations/xor.function.test.ts

Added 25 new unit tests across the `comparisons` and `operations` test suites.
Added 2 new disjoint test sets.

added unit tests

---

tsconfig.json

Ultimately, when it comes to the decision over which files to publish in the distributed package, there are two options to consider:
1. Publish both `sources` & `source maps`.
2. Publish neither `sources` nor `source maps`.
This is because, fundamentally, in order for end users to use `source maps` for debugging purposes, they would need the associated `sources` available in the package.
Given that we currently do not currently publish `sources`: option 1 would mean adding `sources` to the package, whereas option 2 would be to remove the `source maps`. And after some `npm publish --dry-run` testing, the differential end result is that adding `sources` would increase the package size by ~100% over removing `source maps`.
Further reading on the discussion: …

remove source maps from distributed package

---

README.md
src/comparisons/disjoint.function.ts
src/comparisons/pairwise-disjoint.function.ts
src/index.ts
test/comparisons/disjoint.function.test.ts
test/comparisons/pairwise-disjoint.function.test.ts
test/constants/testing-constants.ts
test/scale.test.ts

1. `disjoint`: only compares the primary set to its peers.
2. `pairwiseDisjoint`: compares all sets to each other.
In the process of this implementation spliltting, `disjoint` function received a tremendous performance increase. The scale tests showed that its performance improved by will into the 90% range, and all of the worst case scenario tests put it well past 99% time reduction.
<details>
<summary><h4 style="display: inline; margin-bottom: 0;">[original] raw data:</h4></summary>
|              | disjoint(of1) | disjoint(of1, of1) | disjoint(of1, of2) | disjoint(of2, of1) | disjoint(of1, of1, of1) | disjoint(of1, of2, of3) | disjoint(of3, of2, of1) |
|:-------------|:--------------|:-------------------|:-------------------|:-------------------|:------------------------|:-------------- …

added `pairwiseDisjoint` function

---

README.md

The result of using implicit links in the README, makes the raw marginally more legible, in addition to reducing its overall size.
Some light `npm publish --dry-run` testing showed that this refactor reduced the package size by ~500b.

use implicit links in README

---

.eslintrc.json
package-lock.json
package.json

Separated JS & TS linting rules. Removed some unnecessary linting rules, and their respective package dev dependencies.

simplified & optimized eslint

---

.eslintrc.json
package-lock.json
package.json

Also, added explicit use of `@typescript-eslint/parser` in eslint.

removed unused dev-depencies

---

test/constants/multiples.model.ts
test/constants/sort-testing-constants.ts
test/constants/timer.model.ts
test/scale.test.ts

Each of the functions now have 4 additional scale tests. Each new test calls the function `100,000` times, with input Sets that contain a total of `100` entries.
1. `100k ⋅ function(2 Equivalent)`: 2 equivalent Sets of 50 entries each.
2. `100k ⋅ function(5 Equivalent)`: 5 equivalent Sets of 20 entries each.
3. `100k ⋅ function(2 Disjoint)`: 2 disjoint Sets of 50 entries each.
4. `100k ⋅ function(5 Disjoint)`: 5 disjoint Sets of 20 entries each.

added horizontal scale tests

---

src/comparisons/superset.function.ts

Removed duplicate `proper superset` documentation from the `superset` jsdoc.

fixed superset documentation

---

test/comparisons/disjoint.function.test.ts
test/comparisons/equivalence.function.test.ts
test/comparisons/pairwise-disjoint.function.test.ts
test/comparisons/proper-subset.function.test.ts
test/comparisons/proper-superset.function.test.ts
test/comparisons/subset.function.test.ts
test/comparisons/superset.function.test.ts
test/operations/difference.function.test.ts
test/operations/intersection.function.test.ts
test/operations/union.function.test.ts
test/operations/xor.function.test.ts
test/ordering/sort.function.test.ts
test/util/test-sets/array-test-sets.model.ts
test/util/test-sets/date-test-sets.model.ts
test/util/test-sets/enum-test-sets.model.ts
test/util/test-sets/error-test-sets.model.ts
test/util/test-sets/function-test-sets.model.ts
test/util/test-sets/map-test-sets.model.ts
test/util/test-sets/object-test-sets.model.ts
test/util/test-sets/reg-exp-test-sets.model.ts
test/util/test-sets/set-test-sets.model.ts
test/util/test-sets/symbol-test-sets.model.ts
test/util/test-sets/test-sets.model.ts
test/util/test-suite.function.ts

As a followup to #59, where we split the concrete unit tests into generic implementations. This adds implementations of `TestSets<>` for each of the JS and TS builtins:
1. `ArrayTestSets extends TestSets<Array>`
2. `DateTestSets extends TestSets<Date>`
3. `EnumTestSets extends TestSets<Enum>`
4. `ErrorTestSets extends TestSets<Error>`
5. `FunctionTestSets extends TestSets<Function>`
6. `MapTestSets extends TestSets<Map>`
7. `ObjectTestSets extends TestSets<Object>`
8. `RegExpTestSets extends TestSets<RegExp>`
9. `SetTestSets extends TestSets<Set>`

added all builtins unit tests

---

test/util/scale/timer.model.ts

Removes the unnecessary jest output wrapping of `console.log` from `timer.model.ts` around every output.

scale tests write via process.stdout

---

src/comparisons/pairwise-disjoint.function.ts

Added a preface to `pairwiseDisjoint`, which evaluates the first 2 sets against each other, before creating an `allElements` set. Thereby, we can evaluate for equivalent values immediately, without wasting time copying. And only after those first 2 sets are shown to be disjoint do we create a disjoint union, and continue evaluating.
This improves the `pairwiseDisjoint` function tremendously at scale, when rendering false results. The scale tests show that when evaluating low numbers of input sets, and expecting a false result, `pairwiseDisjoint`'s performance improved by at least 60% for all cases. And all of the worst case scenario tests put it well past a 99% time reduction.
Meanwhile, for the expected true cases, where the input sets are all indeed pairwise disjoint, the timing remains …

improved pairwiseDisjoint performance

---

test/comparisons/disjoint.function.test.ts
test/comparisons/equivalence.function.test.ts
test/comparisons/pairwise-disjoint.function.test.ts
test/comparisons/proper-subset.function.test.ts
test/comparisons/proper-superset.function.test.ts
test/comparisons/subset.function.test.ts
test/comparisons/superset.function.test.ts
test/operations/difference.function.test.ts
test/operations/intersection.function.test.ts
test/operations/union.function.test.ts
test/operations/xor.function.test.ts
test/util/scale/timer.model.ts

Added two new tests to each of the `comparisons` and `operations` test suites:
- `many of the same set`: tests `function(6x setA)`
- `many sets (reversed)`: tests `function(setF, setE, setD, setC, setB, setA)`
Added more newlines around the `process.stdout` calls.

added many sets unit tests

---

test/scale/comparisons/disjoint.function.scale.test.ts
test/scale/comparisons/equivalence.function.scale.test.ts
test/scale/comparisons/pairwise-disjoint.function.scale.test.ts
test/scale/comparisons/proper-subset.function.scale.test.ts
test/scale/comparisons/proper-superset.function.scale.test.ts
test/scale/comparisons/subset.function.scale.test.ts
test/scale/comparisons/superset.function.scale.test.ts
test/scale/operations/difference.function.scale.test.ts
test/scale/operations/intersection.function.scale.test.ts
test/scale/operations/union.function.scale.test.ts
test/scale/operations/xor.function.scale.test.ts
test/scale/ordering/sort.function.scale.test.ts
test/util/scale/ansi-format.model.ts
test/util/scale/scale-test-sets.model.ts
test/util/scale/timer.model.ts

Instead of printing every scale test time in one line, they are now separated into line-broken regions. So, most of the scale test suites now output 3 lines, for the `large sets`, `many sets`, and `many times` tests are visually separated into different lines.
Well, the GitHub actions are surely unlikely to report the ANSI colors, we already see this.
But for local runs, the timings are now colored by their relative performance. In order of best to worst performance, the timings are colored as: `purple → blue → green → yellow → red → black`. This gives an at-a-glance view of which tests are most performant, and likewise, which are worst performant.

pretty print timer output

---

src/operations/difference.function.ts

Added a preface to `difference`, which compares elements in the first 2 sets to create the initial `resultSet`.
This improves the `difference` function significantly at scale, when comparing sets with many shared elements. Because, there is no time wasted adding elements to the `resultSet` which are immediately removed, on the first comparison. 
The scale tests show that when taking the `difference` of equivalent sets, we see a performance improvement of ~70 - 80%. And, somewhat surprisingly, even when taking the `difference` of disjoint sets we see a performance improvement of ~15%.
<details>
<summary><h4 style="display: inline; margin-bottom: 0;">[original] raw data:</h4></summary>
|              | diff(of1)       | diff(of1, of1)  | diff(of1, of2)  | diff(of2, of1)  | diff(of1, of1, …

improved difference performance

---

test/unit/comparisons/disjoint.function.test.ts
test/unit/comparisons/equivalence.function.test.ts
test/unit/comparisons/pairwise-disjoint.function.test.ts
test/unit/comparisons/proper-subset.function.test.ts
test/unit/comparisons/proper-superset.function.test.ts
test/unit/comparisons/subset.function.test.ts
test/unit/comparisons/superset.function.test.ts
test/unit/operations/difference.function.test.ts
test/unit/operations/intersection.function.test.ts
test/unit/operations/union.function.test.ts
test/unit/operations/xor.function.test.ts

Added two new tests to each of the `comparisons` and `operations` test suites:
- `two disjoint sets`: tests `function(setD, setE)`
- `three disjoint sets`: tests `function(setD, setE, setF)`

added disjoint sets unit tests

---

package.json

Webpack, as well as some other bundlers, use the `"sideEffects"` package field in order to tell whether a package can optimally utilize `tree shaking` in the bundling process.
This library contains individual utilities. And each of those should be tree shakable by bundlers. If you only want to serve `difference` out of this package, you should be able to do so.
- [the webpack guide to tree shaking](https://webpack.js.org/guides/tree-shaking)
- [what does webpack expect from a package with "sideEffects" false](https://stackoverflow.com/questions/49160752/what-does-webpack-4-expect-from-a-package-with-sideeffects-false)
- [a good conversation about whether or not to specify the "sideEffects" field](https://github.com/ai/nanoid/issues/108)

mark the package as side effect free

---

test/unit/comparisons/disjoint.function.test.ts
test/unit/comparisons/equivalence.function.test.ts
test/unit/comparisons/pairwise-disjoint.function.test.ts
test/unit/comparisons/proper-subset.function.test.ts
test/unit/comparisons/proper-superset.function.test.ts
test/unit/comparisons/subset.function.test.ts
test/unit/comparisons/superset.function.test.ts
test/unit/operations/difference.function.test.ts
test/unit/operations/intersection.function.test.ts
test/unit/operations/union.function.test.ts
test/unit/operations/xor.function.test.ts
test/util/test-sets/test-sets.model.ts

Formerly, each of the `comparisons` unit test suites had custom implemented tests at the end of their files. And some of those tests have since become unnecessary due to other standardized test additions. Of those custom tests, there were four that could reasonably be standardized across all of the `comparisons` and `operations` unit tests, such that all tests maintained full code coverage.
Added four new tests to each of the `comparisons` and `operations` test suites:
1. `2 disjoint sets with decreasing cardinality`: tests `function(setA, setD)`.
2. `2 disjoint sets with increasing cardinality`: tests `function(setD, setA)`.
3. `empty, all sets, & universal`: tests `function(∅, setA, setB, setC, setD, setE, setF, U)`.
4. `universal, all sets, & empty`: tests `function(U, setF, setE, …

standardized the custom comparisons unit tests

---

README.md
src/comparisons/proper-subset.function.ts
src/comparisons/proper-superset.function.ts
src/comparisons/subset.function.ts
src/comparisons/superset.function.ts

Simplified, and in some instances corrected, the documentation in the comparisons function files, as well as in the README.

fixed comparisons documentation verbiage

---

jest.config.ts

There is a bug between Jest and newer versions of V8, where code coverage of a single file is overwritten between separate tests, instead of being merged. So, a single file which is referenced in multiple tests will only report code coverage from the most recent test that was run.
In the case of this repository, the function _(file)_ being under-reported was `equivalence`. Which is used to prove the efficacy of some other unit tests. So it was being reported as missing branch coverage.
- https://github.com/jestjs/jest/issues/14766
- https://github.com/nodejs/node/issues/51251

fix Jest V8 code coverage reporting

---

src/index.ts

Latest version breaks because imports are missing .js extension.

fix: import esm module requires extension

---

test/util/test-sets/big-int-test-sets.model.ts
test/util/test-suite.function.ts

Turns out that I missed one of the JS primitives, when originally writing these unit test suites. And that was `boolean`.
If there was a way to short circuit the test suite, and only use as many sets as there are unique values, maybe `boolean` tests would be viable. But these tests currently expect at least 10 unique values for the given type. I think that `bigint` supports at least 10 unique values.

bigint test suite

---

src/comparisons/disjoint.function.ts
src/comparisons/equivalence.function.ts
src/comparisons/pairwise-disjoint.function.ts
src/comparisons/proper-subset.function.ts
src/comparisons/proper-superset.function.ts
src/comparisons/subset.function.ts
src/comparisons/superset.function.ts
src/operations/difference.function.ts
src/operations/intersection.function.ts
src/operations/union.function.ts
src/operations/xor.function.ts
src/ordering/sort.function.ts

The input sets are publicly declared as either `Set<T>` or `ReadonlySet<T>`. And in TypeScript, `Set` extends `ReadonlySet`. Because it is functionally the same type but with extra properties for mutability.
When this library was initially written, each function exposed a generic `S` that extended `ReadonlySet`. This guaranteed that the return type would be the same as the input set types. And, when declared types were added to this library in `v1.1.0`, that typing paradigm `S` remained. But for internal use only, as only explicit cases for `Set -> Set` and `ReadonlySet -> ReadonlySet` are exposed in the distribution.
Because there are declared types for each function, that generic is no longer internally necessary. `Set` extends `ReadonlySet`. So each function can be internally typed …

simplified set typing
